ITUniversity.Tasks.Web/Controllers/TaskController.cs
using AutoMapper;

using ITUniversity.Tasks.API.Services;
using ITUniversity.Tasks.Web.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ITUniversity.Tasks.Web.Controllers
{
    /// <summary>
    /// Контроллер для работы с задачами
    /// </summary>
    [Authorize(Roles = "user, admin")]
    public class TaskController : Controller
    {
        private readonly ITaskAppService taskAppService;

        private readonly IMapper mapper;

        /// <summary>
        /// Инициализировать экземпляр <see cref="TaskController"/>
        /// </summary>
        /// <param name="taskAppService">Сервис для работы с задачами</param>
        /// <param name="mapper">Маппер</param>
        public TaskController(ITaskAppService taskAppService, IMapper mapper)
        {
            this.taskAppService = taskAppService;
            this.mapper = mapper;
        }

        /// <summary>
        /// Получить страницу со списком задач
        /// </summary>
        [HttpGet]
        public IActionResult Index()
        {
            var incoming = taskAppService.GetMyIncoming();
            var outgoing = taskAppService.GetMyOutgoing();
            return View(new TasksModel { Incoming = incoming, Outgoing = outgoing });
        }

        /// <summary>
        /// Получить страницу добавления задачи
        /// </summary>
        [HttpGet]
        public IActionResult Add()
        {
            return View(TaskCreateModel.New);
        }

        /// <summary>
        /// Удалить задачу
        /// </summary>
        /// <param name="id">Идентификатор задачи</param>
        [HttpPost]
        public IActionResult Delete(long id)
        {
            taskAppService.Delete(id);

            return Json(new { success = true });
        }

        /// <summary>
        /// Получить страницу с описанием задачи
        /// </summary>
        /// <param name="id">Идентификатор задачи</param>
        [HttpGet]
        public IActionResult Details(long id)
        {
            var dto = taskAppService.Get(id);

            return View(dto);
        }

        /// <summary>
        /// Получить стрицу редактирования задачи
        /// </summary>
        /// <param name="id">Идентификатор задачи</param>
        [HttpGet]
        public IActionResult Edit(long id)
        {
            var taskDto = taskAppService.Get(id);
            var model = mapper.Map<TaskEditModel>(taskDto);

            return View(model);
        }
    }
}

ITUniversity.Tasks.Web/Controllers/UserController.cs
using AutoMapper;

using ITUniversity.Tasks.API.Services;
using ITUniversity.Tasks.Web.Models;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ITUniversity.Tasks.Web.Controllers
{
    /// <summary>
    /// Контроллер для работы с пользователями
    /// </summary>
    [Authorize/*(Roles = "admin")*/]
    public class UserController : Controller
    {
        private readonly IUserAppService userAppService;

        private readonly IMapper mapper;

        /// <summary>
        /// Инициализировать экземпляр <see cref="UserController"/>
        /// </summary>
        /// <param name="userAppService">Сервис для работы с пользователями</param>
        /// <param name="mapper">Маппер</param>
        public UserController(IUserAppService userAppService, IMapper mapper)
        {
            this.mapper = mapper;
            this.userAppService = userAppService;
        }

        /// <summary>
        /// Получить страницу с пользователми
        /// </summary>
        [HttpGet]
        public IActionResult Index()
        {
            var dtos = userAppService.GetAll();
            return View(dtos);
        }

        /// <summary>
        /// Получить страницу редактирования пользователя
        /// </summary>
        /// <param name="id">Идентификатор пользователя</param>
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var userDto = userAppService.Get(id);
            var model = mapper.Map<UserEditModel>(userDto);
            if (userDto.Role != null)
            {
                model.RoleId = userDto.Role.Id;
            }
            return View(model);
        }
    }
}

ITUniversity.Tasks.Web/Views/Shared/_Layout.cshtml
@using ITUniversity.Runtime.Session

@inject IAppSession AppSession

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IT-University</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Пользователи", "Index", "User", null, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Задачи", "Index", "Task", null, new { @class = "nav-link text-dark" })
                        </li>
                    </ul>
                </div>
                <span class="navbar-text" style="margin-right: 10px;">@(AppSession.UserLogin)</span>
                <a href="@Url.Action("Logout", "Account")" class="btn btn-outline-info">Выйти</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ITUniversity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>